version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - psqldb:/var/lib/postgresql

  rotnote:
    image: rotnote
    restart: always
    ports:
        - 8000:8000
    environment:
        DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/postgres?sslmode=disable
        SECRET_KEY: ${ROTNOTE_SECRET_KEY}
volumes:
  psqldb:
    external: true
